name: canvas_test_examples
description: An example of how to use the canvas_test package
version: 0.1.0
homepage: https://github.com/bluefireteam/canvas_test
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^0.0.1
  flutter_test:
    sdk: flutter
  test: ^1.17.10
  canvas_test:
    path: ../

