name: canvas_test
description: A package with classes to help testing applications using the canvas
version: 0.2.0
homepage: https://github.com/bluefireteam/canvas_test

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: ^1.17.10
  vector_math: '>=2.1.0 <3.0.0'

dev_dependencies:
  flame_lint: ^0.0.1
